### ISSUE TITLE
Index offset may not survive some processes

### ISSUE THREAD

**Issue by lrosenthol** [WICG/webpackage#11]
However, because the header of the is document is text - most sniffers will consider this a text file and treat it accordingly (eg. screwing up line endings).  If this happens, then all byte offsets will be incorrect and the file will be unable to load.

Consider finding a way to fool the sniffer or move to a binary format.

**Comment by bmeck** [comment]
These offsets can also suffer if the package:

1. is re-ordered (perhaps due to priorities)

    Signatures are Headers+Body of a content resource currently which means it can be re-ordered fairly simply and maintain the signatures still. This was talked about on a phone call as being possible, particularly since the boundaries allow the Content Index Entities to keep the same hash.

2. streamed in such a way as chunked encoded where encoding boundaries/headers could change the exact offsets.

   In order for a Content Index to have these offsets for a streaming resource it would need to be at the end of file and not allow removing the encoding boundaries/headers. This seems a bit wasteful since a stream would need to track these offsets if the size of streamed chunks is not known ahead of time.

In any case, both of these have a need to recalculate the Package-Signature if the offsets change. Doing so while streaming would mean that Package-Signature also would need to occur at the end of file, presumably as a trailer.

**Comment by jyasskin** [comment]
#36 takes the index structure out of the signed content, so it can be re-generated by any process that invalidates its offsets. I think this is fixed.
