### ISSUE TITLE
Officially rename webpackage to another name.

### ISSUE THREAD

**Issue by TheLarkInn** [WICG/webpackage#113]
I'd like to propose that we explore an alternative name for webpackage. Although [webpack](https://webpack.js.org/) is a separate tool in concerns of responsibilities from webpackage, I've already had a variety of confusion expressed from our userbase about what webpackage is and how it relates to webpack. 

Maybe some options: 
* WebParcel
* WebZip
* WebDistro

Mind you these are off the cuff, but I'd like to formally spin up the work involved to start exploring a replacement if there are no objections.

**Comment by rektide** [comment]
I can't think of a better alternative.

Keep in mind that the spec needs magic-bytes. Any replacement candidate names OUGHT also have a fair and sensible set of magic bytes that emphasize the name. Anything not having good magic-bytes is, imho, a major downgrade in DX.

**Comment by TheLarkInn** [comment]
> spec needs magic-bytes

Would you mind expanding on this?

**Comment by rektide** [comment]
> Would you mind expanding on this?

These magic-bytes are defined in https://tools.ietf.org/html/draft-yasskin-dispatch-web-packaging-00#section-2.2 .

**Comment by jyasskin** [comment]
This is related to https://github.com/WICG/webpackage/issues/57#issuecomment-304945769, but thanks for filing an explicit issue about it.

I've started calling the [bundling spec](https://github.com/WICG/webpackage/pull/98), well, "bundling" for lack of a better name, but WebParcel, WebZip, WebBundle, or some other name is fine with me. WebDistro reminds me a bit too much of Linux.

I don't think there will be any trouble finding decent magic bytes for whatever we choose. Even if we keep the cute use of emoji, there are enough emoji to match almost anything.

**Comment by rektide** [comment]
I don't super look forward to explaining to everyone that the name changed. That personally feels like a fright & complication I'd rather not deal with, & I personally would rather roll with it as is.

WebBundle would be accurate though.

**Comment by TheLarkInn** [comment]
I guess my goal here is: 

A name that doesn't include the following: webpack, bundle, bundler, module bundler, etc.

Anything that could be confused with webpack, module bundler, rollup bundler, etc.

Unless I've missed some recent changes to this spec, this is to describe a compression and peer to peer transfer/transmission protocol no? And not static bundling/compiling of web assets?

**Comment by rektide** [comment]
If we're going no clash with anything at all, [Parcel](https://github.com/parcel-bundler/parcel) is out too.

Of the original list, that leaves WebDistro (too linuxy) and WebZip (it's not a zip and that's confusing).

Are we going to have to leave the visible spectrum to find a color we can paint this bikeshed?

**Comment by KenjiBaheux** [comment]
Sean, it's a way to bundle web resources: a format containing an index, a
manifest and resources.

Webwrap, Webcontainer, Webpacket?

**Comment by cramforce** [comment]
I think there is a systematic way to go about the naming conflicts itself. Using a generic naming like "Package" or "Bundle" will always lead to conflicts. Certainly Web "Animations" and CSS "Grid" conflicted with another project here and there. The conflicts on the generic term cannot be avoided. This is where the "Web" prefix comes in. Being customary for modern web specs it disambiguates the generic term.

Now, there is a special case, since webpack also uses the web prefix and hence there is genuine chance of confusion, especially given the similar domain that webpack and Web Packaging operate in (webpack would likely eventually become one of the most popular ways to make Web Packages).

With that I agree that "Web Packaging" should be reconsidered to avoid the confusion with "webpack" outlined above, but I'd not further constrain the namespace.

Given the current use of terminology in this project it seems to me like "Web Bundle" or "Web Bundling" seems like the most straightforward choice.

**Comment by rektide** [comment]
Wrap doesn't make intuitive sense to me. Container is hella over loaded. Packet is a weird clash with network layer, where packet is typically the smallest unit not a bundle of other things.

**Comment by jyasskin** [comment]
@TheLarkInn Do you still dislike names involving "bundle" given @cramforce's argument and the fact that the format in #98 is actually about static bundling of web assets?

It's likely that we'll be referring to this as "the specifications formerly known as web packaging" for a while, but since the specification has split anyway, and packaging was too associated with other complications in people's minds, I'm definitely in favor of calling the two halves something other than packaging.

We have roughly 2 categories of options:

1. A purely descriptive name
   1. WebBundle
   1. WebZip: follows the precedent of things like 7zip and correctly implies that resources can be directly accessed without decompressing a prefix of the file.
1. A made-up codename, which can avoid colliding with anything else. I don't have any good ideas here yet, but clever suggestions with good rationales could win out.

I also want to be clear that I don't know who @rektide is, and while their suggestions are welcome, they're not going to determine the name.

**Comment by TheLarkInn** [comment]
I do like WebZip. It makes it very clear what is happening.

**Comment by Jxck** [comment]
HTTP has a HPACK now.
so I like WPACK for this.

**Comment by BigBlueHat** [comment]
> I do like WebZip. It makes it very clear what is happening.

Not sure PKWARE would agree there... http://www.pkware.com/documents/casestudies/APPNOTE.TXT ...nor the ISO http://www.iso.org/iso/home/store/catalogue_tc/catalogue_detail.htm?csnumber=60101

Also, WebBundle seems to be the most promising name (of the current list) so far, though HTTPack is maybe closest. 😄

**Comment by edwardkenfox** [comment]
I think webpackage is most straightforward, but also think WebBundle makes sense, too. I came up with "Site Packaging" as well "HTTP Container" as alternative names, yet, thinking to myself "HTTP Container" sounds more of a low-level thing and might not suit the need for this.

**Comment by jyasskin** [comment]
I've been referring and getting others to refer to the components as "Signed Exchanges" and "Bundles", but the "Web Packaging" name for the overall project has enough mindshare, dating back to https://www.w3.org/TR/2015/WD-web-packaging-20150115/, that I don't think we can change it. The IETF is using the ["wpack"](https://www.ietf.org/mailman/listinfo/wpack) shorthand. All of this is close to "webpack", but it's not directly ambiguous, so I think it's the best we can do.
