### ISSUE TITLE
Specify the cache lifetime of a signed exchange

### ISSUE THREAD

**Issue by jyasskin** [WICG/webpackage#154]
The signature's expiry limits when you can receive the exchange. The HTTP cache control headers limit when you can use the exchange after it's successfully received.

It's not obvious what the policy should be, but a simple policy is to say that the resource expires from the cache at the earlier time of the signature expiration and the cache expiration.

We also need to specify how the resource is revalidated after it expires.
1. The first use needs to be similar to [`<link rel=preload>`](https://w3c.github.io/preload/#link-type-preload) so that it's not revalidated during that first use.
1. Subsequent uses can either [update signature validity](https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#updating-validity) if the signature's expired, or use a conditional request if the cache information's expired. Once the signature's expired, remember that the etag isn't trustworthy.

**Comment by mnot** [comment]
Hm. If we're talking about signed exchanges that are transferred over "normal" HTTP (i.e., not inside a bundle), the HTTP caches receiving it will treat it like any other response with freshness controls. You can't really override that, since not all caches receiving it will understand the signature.

If we're talking about signed exchanges inside a bundle -- which is effectively a different protocol -- it makes sense to figure out what the basis of the freshness lifetime is. I'm thinking it might make sense to make the `date` of the signature input to [calculating age](http://httpwg.org/specs/rfc7234.html#expiration.model).

**Comment by jyasskin** [comment]
This is now sketched at https://github.com/WICG/webpackage/blob/master/explainer.md#signed-exchange-loading-sketch via #173.

For now, we're omitting third-party signed exchanges from the HTTP cache entirely. If we [add them later](https://github.com/WICG/webpackage/blob/master/explainer.md#to-consider-cache-the-inner-exchange), I think we'll have them live the shorter of the signature validity and the HTTP cache freshness expiration.

As Mark says, first-party signed exchanges are cached purely according to their HTTP headers.
