### ISSUE TITLE
openssl review needed: go/signedexchange/README.md

### ISSUE THREAD

**Issue by nyaxt** [WICG/webpackage#245]
@davidben @irori, would you take a look at self-signed cert generation instructions at https://github.com/WICG/webpackage/tree/master/go/signedexchange#creating-our-first-signed-exchange ?

**Comment by davidben** [comment]
You probably should mention that `example.org` should (I assume) be replaced with your origin.

Does `<(echo "1.3.6.1.4.1.11129.2.1.22 = ASN1:NULL\nsubjectAltName=DNS:example.org")` work? That prints a literal `\n` for me, not a newline, and indeed the instructions cause my `openssl` to break. (Had you run this before? Maybe we use different shells? I'm just using bash.) Perhaps `<(echo "1.3.6.1.4.1.11129.2.1.22 = ASN1:NULL"; echo "subjectAltName=DNS:example.org")` 

Otherwise LGTM.

**Comment by nyaxt** [comment]
Thanks!

> Maybe we use different shells?
I was using zsh and the shell expandeds it. Added `-e` param so that echo will expand it if the shell doesn't.
