### ISSUE TITLE
Document Adobe's use cases

### ISSUE THREAD

**Issue by jyasskin** [WICG/webpackage#32]
@lrosenthol, could you describe the use cases you're interested in for the packaging format, either in this issue or as a PR against the [`README.md`](https://github.com/dimich-g/webpackage/blob/master/README.md)?

**Comment by lrosenthol** [comment]
@jyasskin I became involved in this project due to Adobe's involvement in the [Web Publications](https://w3c.github.io/dpub-pwp/) work at the W3C and the filing of issue #3 .  However, we are also interested in the work with Node & Electron, as they are technologies that we use internally.

Personally, I have a very long (30+ year) history with archiving and packaging formats having been one of the founders of Aladdin Systems, which was responsible for [StuffIt](https://en.wikipedia.org/wiki/StuffIt).

**Comment by jyasskin** [comment]
Thanks, so http://w3c.github.io/dpub-pwp-ucr/index.html covers the use cases? Also thanks for explaining your background.

**Comment by lrosenthol** [comment]
Yes, that would be the right document to work from.

**Comment by jyasskin** [comment]
Looking at dpub-pwp-ucr, it doesn't mention signing the publication. Given your other comments, I assume Adobe does have requirements around signatures, so could you write them down somewhere?

I'll also admit that the Chrome folks are going to prioritize letting browsers give a package the [same origin](https://html.spec.whatwg.org/multipage/browsers.html#same-origin) as content loaded over HTTPS, over any Web Publications requirements, if there's a conflict. I don't see any impossible conflicts yet, especially if we allow multiple certificates to sign the same package, but FYI.

**Comment by lrosenthol** [comment]
@jyasskin Nothing Adobe-centric here - just me representing the PWP community as one of the editors of the works in progress.  

Signing a publication is simply one well-established model to establish trust on a set of "off the web" resources - just as it is here with web packages.  That's what this entire discussion is about - how to establish that trust so that both the user and the UA feel safe in using some/all of the resources in a package/publication.

The entire work on sub-domains is also something interesting to the world of publications, where a single "physical" publication may actually be a collection of publications - in which case, sub-domains would serve to help with a variety of potential problems.
