### ISSUE TITLE
Reflecting the URL leads to content sniffing bugs

### ISSUE THREAD

**Issue by molnarg** [WICG/webpackage#321]
When a server returns a web package in the application/signed-exchange format, it'll embed the request URL in the returned binary blob in the fallbackUrl field. Depending on the server implementation, the encoding of bytes of the URL might vary. Some implementation might choose the easiest solution, which is to just reflect whatever representation the client sends.

This is problematic, because this gives attackers an easy injection point within the first few bytes of the file, which can be turned into code running in the victim origin using content sniffing. The Adobe PDF parser for example ignores the unknown prefix bytes if it finds a valid PDF signature within the first 1kb of the file.

The "x-content-type-options: nosniff" header instruct browsers to not do content sniffing, but plugins can choose to (and in many cases do) ignore them. Because of this, the usual suggestion is to host partially user controlled binary files only on sandbox domains (when it's not possible to sufficiently escape the user controlled parts, which is usually not the case).

This demo page is not vulnerable to this, because it requires a special Accept request header: https://azei-package-test.com/ Clients that can't interpret the web package format will never send this header, so they'll never see the signed exchange file format.

One solution would be to use some kind of encoding for all reflected values (e.g. base64) to avoid introducing a valuable injection point in the first place.

**Comment by twifkak** [comment]
(Just chiming in to provide some detail; don't consider my response authoritative as I'm not an owner of this repo.)

If I'm reading correctly, the spec defines [fallbackUrl as an absolute URL](https://wicg.github.io/webpackage/draft-yasskin-httpbis-origin-signed-exchanges-impl.html#application-signed-exchange) and then defines [absolute URLs per the URL parser](https://wicg.github.io/webpackage/draft-yasskin-httpbis-origin-signed-exchanges-impl.html#terminology), and the URL parser requires [only URL code points in the path](https://url.spec.whatwg.org/#path-state), and here are [the URL code points](https://url.spec.whatwg.org/#url-code-points).

Of course, even if the URL is base64-encoded, the attacker could modify the length of the fallback URL to manipulate those 2 bytes.

**Comment by nyaxt** [comment]
cc: @sleevi @jyasskin 

Thanks for filing the issue.

Would you mind expanding the attack scenario details?
If I understand this correctly, the assumptions are:
1. A Target HTTP User-Agent (more generic than web browsers, incl. plugins) runs a content parser that ignores unknown prefix bytes.
2. A SXG server which returns SXG of `fallbackUrl` which reflects the request URL enough to inject an attack vector.
3. It is useful for the attack vector to run on an HTTP origin which the SXG server runs on.

I buy that 1 and 3 can theoretically hold but I'm not sure if 2 holds, since there are multiple restriction to the URL.
- The server should not return a sxg unless the absolute url is valid, incl. the URL code points restriction @twifkak mentioned.
- The server need to host the resource, otherwise the server should not be able to generate a sxg since it would not have valid certificates for the resource.
  - Still, bad servers may still create sxgs containing a 404 response. We may want to disallow sxg enclosing non-2XX responses in the format spec.

**Comment by jyasskin** [comment]
@molnarg Note that the fallback URL isn't supposed to be reflected from the request URI. Instead, it's the canonical location of the signed content, which should be completely under the control of the server.

That said, I can't rule out a naive server making the mistake you're suggesting. Such a server might also reflect data from some HTTP request headers (as Google did in https://crbug.com/901477#c18) into an early part of the signed exchange, which provides another injection point a couple hundred bytes in. For that matter, even the start of the body may be within the first 1kB, if the server chooses to reflect attacker-controlled data into the body, but I suppose that's a vulnerability even without signed exchanges, and so out of the scope of your complaint.

I assume that base64-encoding works because nearly all file signatures include a byte outside the base64 alphabet?

@twifkak, unfortunately, the URL parser doesn't limit its accepted input to URL code points. Code points outside that range cause non-fatal [validation errors](https://url.spec.whatwg.org/#validation-error), and then the parser continues. [`%PDF-`](https://en.wikipedia.org/wiki/List_of_file_signatures) is accepted and can be reflected back out. This prevents the server's parsing of the request URL from protecting us, even if the server has a conformant URL parser.

So, the question is what to do. I don't like the idea of base64-encoding every bit of data that a server might reflect, but it's a last-resort option.

Would it be acceptable to just add a security consideration that servers must not naively reflect the request URL or request headers and then sign them?
