### ISSUE TITLE
Signature Validation of Bundled Exchanges

### ISSUE THREAD

**Issue by irori** [WICG/webpackage#472]
Bundled Exchanges spec [defines the format of signature section](https://wicg.github.io/webpackage/draft-yasskin-wpack-bundled-exchanges.html#signatures-section) but doesn't define how to validate it.

I can imagine how validation works; To validate `(authority, sig, signed)` triple in `vouched-subsets`, a client would run an algorithm similar to the [SXG's Signature validity](https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#signature-validity) but its entities replaced as follows:

- `requestUrl` -> `signed.subset-hashes` which includes `whatwg-url`
- `responseHeaders` -> `signed.subset-hashes` which includes `header-sha256`
- `payload` -> `payload` in the responses section
- `signature` -> `sig`
- `integrity` -> `payload-integrity-header` included in `signed.subset-hashes`
- `validity-url` -> `signed.validity-url`
- `cert-sha256` -> `signed.auth-sha256`
- `date` -> `signed.date`
- `expires` -> `signed.expires`
- `certificate-chain` -> `authorities`
- `main-certificate` -> `authorities[authority]`

Does this align with your idea? @jyasskin

Questions:

- Will signing message be the `signed` binary string itself? It doesn't have the 64-spaces padding nor a context string.
- What's the content of resource at `validity-url`?
- Do the requirements of SXG headers (e.g. no uncached fields) apply to BXG too? Response headers are not included in bundle's metadata, so it'd have to be checked in a later step of loading (it wouldn't be a big deal though).
- What about the certificate requirements?
- Is it possible to unify the algorithm to SXG's validation algorithm? It would make implementation simpler.

**Comment by jyasskin** [comment]
In general, bundle signature checking should happen before the `signed` `bstr` is parsed into fields. Then a resource gets checked against the `subset-hashes` as it's being loaded. Looking at https://wicg.github.io/webpackage/draft-yasskin-wpack-bundled-exchanges.html#load-response, I need to change that to check the `headers` `bstr` against the `header-sha256` before parsing it.

1. To check a TLS-like X.509 certificate's signature, I believe the message needs to be the concatenation of:
   1. A string that consists of octet 32 (0x20) repeated 64 times.
   1. A context string: the ASCII encoding of "Web Package 1". ("Web Package 1 b1" for the b1 implementation version.)
   1. A single 0 byte which serves as a separator.
   1. The `signed` `bstr`.

   For non-X.509 authorities, I think we don't really need that prefix, but I'm not sure if we should keep it just to keep everything uniform.

1. I haven't worked out what the `validity-url` will point to yet. I think it may be the same as in https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#updating-validity with the `signatures` field's value changed from `[ + bytes ]` to the `signatures` CDDL rule from https://wicg.github.io/webpackage/draft-yasskin-wpack-bundled-exchanges.html#signatures-section.

1. Yes, the restrictions on headers will need to be processed while loading the resource, rather than while parsing the metadata. I think the same set of 

1. Also the same certificate requirements as SXG for cross-origin trust.

1. If we want to unify Signed Exchange signature checking with Bundle signature checking, I'd push for changing the SXG `Signature` string ("sigLength bytes holding the Signature header field’s value" from https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#application-signed-exchange) into a format where the signed data can also be checked before it's parsed.

**Comment by irori** [comment]
Thanks, I'm working on a bundle signing tool based on this information. ([WIP code here](https://github.com/irori/webpackage/tree/sign-bundle))

Two additional questions:

- Is `payload-integrity-header` the same format as the SXG signature's `integrity` parameter (like "digest/mi-sha256-03")?
- Is `auth-sha256` the hash of the DER-encoded X.509v3 certificate (that matches SXG's `cert-sha256`), or the hash of the `authority` (= `augmented-certificate`) CBOR item?

**Comment by jyasskin** [comment]
1. My intent is that `payload-integrity-header` is the same format as the SXG signature's `integrity` parameter.
1. My intent is that `auth-sha256` is the hash of the same bytes as the SXG's `cert-sha256`. I think there's a possibility that both of those will change, but  I think they'll change together if they do.

**Comment by irori** [comment]
Now we have signature generation / verification implementation in the Go tools (#490 #493).
