### ISSUE TITLE
Study tlsnotary.org experience

### ISSUE THREAD

**Issue by safinaskar** [WICG/webpackage#477]
Hi. There is a https://tlsnotary.org/ project, which has somewhat similar goal with "Signed HTTP exchanges", i. e. an ability to prove that http(s) exchange was performed. But https://tlsnotary.org/ is different in many aspects. Please, learn their experience

**Comment by jyasskin** [comment]
tlsnotary.org describes an online protocol that depends critically on the timing of messages sent between the auditor (client in web packaging terms?) and auditee (distributor in web packaging terms?), while web packaging intends to work offline. It also says changes in TLS1.2 broke it. So, I don't think it's likely to give useful information to the web packaging effort. If you know of particular experience from that project that's relevant here, I'd still be happy to hear it.

**Comment by safinaskar** [comment]
@jyasskin. I didn't use that project, I just have read that site. tlsnotary also have https://tlsnotary.org/pagesigner.html , i. e. tool for offline proving. But it requires trusted server. And authors propose using Amazon virtual server with published sources

**Comment by twifkak** [comment]
Hi, thanks for the link. I'm just a consumer of the spec, not an author, but here's my attempt to learn from that site.

IIUC, if this worked on TLS1.3, it might be usable as a way to generate SXGs from sites that don't generate one themselves. AFAIK, that's not a goal of web packaging (though I'm not sure I've heard that it's an explicit non-goal). For sites that generate SXGs on request, then doing so is a lot less complex (and thus easier to reason about) than the tlsnotary solution.

OTOH, it alone doesn't solve all the issues necessary to trust the content enough to render it in a user-agent, such as downgrades, cert revocation, and cert misissuance. So a solution built on this would need much of the extra SXG infrastructure anyhow.

In addition, it seems like the PageSigner approach depends on trust in the central "oracle" servers in order to trust the integrity. SXG has some central dependencies (on PKI infra & CT logs), but creating new ones seems risky.
