### ISSUE TITLE
How can I trigger SGX responses from an AMP cache?

### ISSUE THREAD

**Issue by coventry** [WICG/webpackage#502]
Cloudfront recently blogged [a demo](https://blog.cloudflare.com/real-urls-for-amp-cached-content-using-cloudflare-workers/#generating-http-signed-exchanges-with-workers) of "HTTP signed exchanges in action on 1-800-Flowers," using Chrome Beta for Android. Is there a way to replicate that interaction using `curl`, so that the signed exchange is returned and I can inspect the headers? I can't figure out how to get a response via `curl` which includes a `Signature:` header, or otherwise seems to be a signed exchange.

Apologies if this is a bit off-topic for a repo which seems to be mostly focused on the webpackage standard. If there are better places to ask this question, I'd be grateful for pointers.

**Comment by ithinkihaveacat** [comment]
From Google's AMP cache, you can trigger SXG responses via by passing an `accept: application/signed-exchange;v=b3` request header:

```sh
curl -sS --output - -H 'accept: application/signed-exchange;v=b3' https://amp-dev.cdn.ampproject.org/wp/s/amp.dev/
# SXG response
```

From an *origin*, you will typically need to pass both `accept: application/signed-exchange;v=b3` and `amp-cache-transform: google;v="1..100"`:

```sh
curl -sS --output - -H 'accept: application/signed-exchange;v=b3' -H 'amp-cache-transform: google;v="1..100"' https://amp.dev/
# SXG response
```

(You need both headers because there's no reason for origins to return SXGs to browsers--the URL is already "correct" and there's some overhead to processing SXGs.)

This should work the same way when Cloudflare is the origin, but testing just now there seem to be a few issues with the `1800flowers.com` server.

Both of these SXG responses can be piped into the [`dump-signedexchange` binary](https://github.com/WICG/webpackage/tree/master/go/signedexchange#dump-a-signed-exchange-file) to verify the response:

```sh
$ curl -sS --output - -H 'accept: application/signed-exchange;v=b3' -H 'amp-cache-transform: google;v="1..100"' https://amp.dev/ | dump-signedexchange -verify
format version: 1b3
request:
  method: GET
  uri: https://amp.dev/
  headers:
...
```

**Comment by twifkak** [comment]
Some documentation on signed exchanges in AMP is available at https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/signed-exchange/. For future such questions, AMP's [support page](https://amp.dev/support/) recommends Stack Overflow with the [amp-html tag](https://stackoverflow.com/questions/tagged/amp-html). If that fails, you can try #signed-exchanges on http://bit.ly/amp-slack-signup.

**Comment by coventry** [comment]
Thank you both very much for your help!
