### ISSUE TITLE
Serialization format optimized for streaming

### ISSUE THREAD

**Issue by jeffkaufman** [WICG/webpackage#577]
The current web bundle serialization has the index at the beginning, and so requires you to know the sizes and urls of all the resources the bundle will contain up-front.  If a bundle is being generated dynamically, however, it would be nice to be able to start sending out the part of the response that is ready before you necessarily know the full contents of the bundle.

Pre-declaring resources, when possible, is still useful, however, because it allows the consumer of the bundle to know that the bundle will contain a given resource and it shouldn't start independent efforts to acquire it.  Similarly, being able to say that a resource is not in a bundle, either by disclaiming a specific resource or by saying that no more resource declarations will follow, would let the consumer know that it should look elsewhere.

If at some point nested web bundles are supported, being able to stream out part of a nested bundle before the whole bundle is ready without blocking the whole stream would be nice.

For context, I'm looking into whether dynamically generated web bundles could at some point be used for serving a single ad response for multiple ad slots.  Streaming the bundle would allow returning a response for a slot that will soon be visible to the user as soon as it's ready, while allowing more time to complete auctions for ads lower down the page.  I expect a streaming-focused serialization format would be useful to many people who end up dynamically generate web bundles, however.

**Comment by jyasskin** [comment]
Thanks for the concrete use case! We discussed this in #6, where the lack of a concrete use case led me to say we shouldn't support this kind of streaming, so now's a good time to reopen the question.

In some ways, MHTML could be the streamed-generation version of the [random-access bundles format here](https://wicg.github.io/webpackage/draft-yasskin-wpack-bundled-exchanges.html), but I think there's appetite to replace the text bits of MHTML with a binary format, and we can re-use the header representations from the random-access one. MHTML also doesn't have a native way to promise that particular responses will be available later.

Another possible design would be as a sequence of [HTTP/2 frames](https://httpwg.org/specs/rfc7540.html#FrameTypes). (They'd be serialized into a file format rather than actually being in an HTTP/2 connection.) PUSH_PROMISE serves as a way to say that a particular URL will eventually arrive. I don't think there's a way to disclaim a resource, but 1) we could invent one, and 2) I suspect we don't actually need it: the default should be to assume arbitrary resources _aren't_ in any bundle. I suspect we'll want to at least customize this a bit so it embeds fewer assumptions that it's living in a real-time connection.

And, of course, there's the option of matching the random-access bundle format as much as possible and just pulling smaller amounts of inspiration from the above two options.

**Comment by jyasskin** [comment]
We discussed this briefly at the IETF 108 WPACK meeting, and there wasn't support in the room to add a variant of the format that supports streamed generation. It seemed like people were open to being convinced by measurements that it'll actually help, so anyone should feel free to re-open this bug with more evidence that it'll pay off.
