### ISSUE TITLE
Support Ed25519 signature in the signatures section of Web Bundles

### ISSUE THREAD

**Issue by horo-t** [WICG/webpackage#669]
The [revived `signatures` section](https://github.com/WICG/webpackage/blob/main/extensions/signatures-section.md)’s `authority` only supports the certificate of DER-encoded X.509v3 certificate (with optional OCSP and SCT). 
If we just want to sign the content with the ED25519 algorithm, we don’t need the X.509 certificate format. We just need to keep the 32 bytes of the ED25519 public key.
So I think we should update the CDDL of the `signatures` section to support the raw ED25519 key.

Note: Signed HTTP Exchange specification does support it by the [`ed25519key` parameter in the signature header](https://datatracker.ietf.org/doc/html/draft-yasskin-http-origin-signed-responses-09#section-3.1).

**Comment by jyasskin** [comment]
Because the [`augmented-certificate` rule](https://datatracker.ietf.org/doc/html/draft-yasskin-http-origin-signed-responses-09#section-3.3) starts with `{cert: bytes, ...`, we can distinguish certificate-based authorities from ed25519 authorities by encoding those as `{ed25519key: bytes}`. So the new `authority` definition becomes:

```cddl
authority = augmented-certificate / ed25519-authority

ed25519-authority = {ed25519key: bytes}
```

We also need to specify in here how to validate the signature, possibly by referring to the algorithm in https://datatracker.ietf.org/doc/html/draft-yasskin-http-origin-signed-responses-09#section-3.5.

----
There's a potential design problem that I think we've already accepted. https://github.com/paseto-standard/paserk#examples-of-invalid-paserks-in-a-paseto-footer says 
> Even though a public key might seem harmless, it risks the encouragement of in-band negotiation. This could result in users trusting the attacker-provided public key associated with a PASETO, which would bypass the security offered by the security token. Therefore, this use case MUST NOT ever be permitted.

Putting the Ed25519 public key into the bundle makes it possible to write software that verified the bundle against that key without checking that the key is valid. However, the rest of the design includes an X509 certificate in the bundle, and that *also* includes a public key that allows verifying the bundle without checking the certificate's validity. If it's ok to include the leaf certificate and trust client software to validate its validity, it should also be ok to trust client software to validate the Ed25519 key's validity.

**Comment by hayatoito** [comment]
[Issue Triage]
Let me close this issue since `signatures` section was removed.
