### ISSUE TITLE
How to converge Subresource Loading with WebBundle APIs, `<script type=webbundle>`, with Bundle Preloading proposal

### ISSUE THREAD

**Issue by hayatoito** [WICG/webpackage#699]
Let's start a discussion how to converge the current [Subresource Loading with WebBundles] with the [Bundle Preloading] proposal.

Regarding their declarative syntax, [Subresource loading with WebBundles] is using this syntax:

```html
<script type=webbundle>
    {
        "source": "foo.wbn",
        "resources": ["css/a.css", "css/b.css"]
    }
</script>
```

while the Bundle Preloading is using this syntax:

```html
<script type="bundlepreload">
      {
          "source": "%PUBLIC_URL%/static.wbn",
          "resources": [
               "%PUBLIC_URL%/static/js/2.f2a9fc33.chunk.js",
               "%PUBLIC_URL%/static/js/3.b6022136.chunk.js",
               "%PUBLIC_URL%/static/js/runtime-main.2f0e8e04.js",
               "%PUBLIC_URL%/static/js/main.4b569d21.chunk.js",
               "%PUBLIC_URL%/static/css/main.a617e044.chunk.css",
               "%PUBLIC_URL%/static/media/logo.6ce24c58.svg"
              ]
          }
</script>
```

This example is taken from [here](https://github.com/WICG/bundle-preloading/blob/main/prototypes/examples/create-react-app/public/index.html).

I'm wondering how we can converge the syntax as much as possible. I know they solve slightly different goals, however, I think there are many common factors, and [Bundle Preloading] is listed as a target of _v2_ in the Subresource Loading's [long term plan](https://github.com/WICG/webpackage/issues/648).

We'd appreciate any ideas or opinions what is the best way to converge both as much as possible.

Just for reference, [Speculation Rules] try to have a flexible syntax for defining what outgoing links can be prepared speculatively before navigation. I'm wondering how we can achieve the same goal to have a flexible syntax which is expressive enough to cover both cases

Before we ship [Subresource Loading with WebBundles] MVP, we'd like to make sure the syntax used there is naturally extended to cover [Bundle Preloading] too.

[Subresource Loading with WebBundles]: https://github.com/WICG/webpackage/blob/main/explainers/subresource-loading.md
[Bundle Preloading]: https://github.com/WICG/bundle-preloading/
[Speculation Rules]: https://jeremyroman.github.io/alternate-loading-modes/speculation-rules.html

Related issues are: #648, #670, #697

**Comment by hayatoito** [comment]
Just an idea, I'm wondering whether we can converge the syntax surface by introducing, such as, `use_cache` or something, in JSON?

For example

```html
<script type=webbundle>
    {
        source: "foo.wbn",
        use_cache: true,
        resources: ["css/a.css", "css/b.css"]
    }
</script>
```

- If `use_cache` is true, this behaves as Bundle Preloading does.
- If `use_cache` is false, this behaves as Subresource Loading with Web Bundles does.
- Note that either the name of `use_cache`, or its default value (true or `false)`, doesn't matter much at this point. We can find a good name or a good default value later.

Is there any implications if we share a syntax in this way? If I miss something, please let me know that!

**Comment by felipeerias** [comment]
@hayatoito

I'm having some trouble understanding which resources would be affected by `use_cache: false`.

For example, with this code:

```html
<script type="webbundle">
{
   source: "./bundle.wbn",
   resources: ["one.png", "two.png", "three.png"],
   use_cache: false
}
</script>

<img src="one.png"/>
<img src="two.png"/>
```

My understanding is that the browser would not fetch `one.png` and `two.png` individually; instead, it would fetch `bundle.wbn` and retrieve those two resources from there.

This is pretty much how it would work for Bundle Preloading as well. In our proposal, all three resources would then be stored in the regular HTTP cache by default (we are looking into using `cache_name` to select a specific cache, like in your proposal).

With `use_cache: false`, which resources would end up in the cache? None of them? All except `three.png`?

**Comment by felipeerias** [comment]
I have also been looking at errors and edge cases. These are some of them, with our interpretation of what would be the right behaviour for each:

- client is not able to request a bundle
  * individual resources are fetched one by one as needed by the document, receiving the same data as if they were requested in a bundle
- bundle includes an error response (e.g. 404) for a resource
  * client does not need to request the resource individually again
  * what happens when the client requests a resource that exists but is outside the scope of the bundle? should we return a specific error code for this case?
- bundle does not include _any_ response for a requested resource
  * this is an error on the part of the server
  * what should the client do?
- server returns more resources than what was initially requested
  * could happen with a server that does not understand subsetting and simply returns the whole bundle file
  * we could either discard those extra resources, or store them but only make them available after they have been requested in another preload tag

**Comment by hayatoito** [comment]
Thanks for the feedback!

> With use_cache: false, which resources would end up in the cache? None of them? All except three.png?

The current behavior of "Subresource Loading" (which is use_cache: false here) is:
A browser don't use a HTTP cache at all for an individual subresource. No read or no store.
A HTTP cache is only used for a bundle itself.

**Comment by felipeerias** [comment]
@hayatoito

Thank you very much for the explanation.

In [the example above](https://github.com/WICG/webpackage/issues/699#issuecomment-969840045) this means that only `bundle.wbn` would be stored in cache, right?

With Bundle Preloading, only individual resources would be stored in cache. We do this because the bundle that the client receives (not the one stored in the server) will probably change a lot, because its contents depend on the resources listed on each tag and on the state of the cache when the preloading request is made.

What is the use case that you are addressing with `use_cache: false`?

**Comment by hayatoito** [comment]
Thanks!

How to cache for each sub resources in each webbundle has been a tricky issue for us. As far as I remember, several approaches have been proposed. e.g. [Dynamic bundle serving with WebBundles](https://docs.google.com/document/d/11t4Ix2bvF1_ZCV9HKfafGfWu82zbOD7aUhZ_FyDAgmA/edit), ResourceBundles, BundlePreloading, and maybe more coming?

That's a reason we can't have it in V1, and explore this area in v2 once we get more insights and feedback in real use cases.

**Comment by hayatoito** [comment]
Update:

Chromium is doing an origin trial for Subresource Loading with Web Bundles.

Given that we've got a positive feedback from OT participants, the next important step is to update several Web standards, such as `<script>` in HTML Standards, Fetch and etc, as a preparation for shipping MVP (aka v1 #648).

If someone finds any concerns about the current `<script>`-based syntax and its semantics which may be an issue for our long term plan (v2, v3), we'd appreciate it if you can share it!

We want to find any potential compatibility issues between the current one (v1) and future ones (v2, v3,...), as early as possible, before trying to update relevant Web standards so that we don't regret anything.



- [The draft one for `<script>`](https://docs.google.com/document/d/1GEJ3wTERGEeTG_4J0QtAwaNXhPTza0tedd00A7vPVsw/edit#heading=h.y88lpjmx2ndn)

**Comment by hayatoito** [comment]
[Issue Triage]
Let me close this tentatively.
