### ISSUE TITLE
Loading in a secure or insecure context?

### ISSUE THREAD

**Issue by lrosenthol** [WICG/webpackage#7]
While there is a good discussion about the need to handle separate (and unique) origins [here](https://github.com/dimich-g/webpackage#use-case-a-web-page-with-a-resources-from-the-other-origin), it's not clear whether such content should be loaded in a secure (https-like) or insecure (http) context - and whether it being signed influences that choice.

**Comment by bmeck** [comment]
I think this is a symptom of including the transfer protocol in the package content-location.

Thoughts for browser behavior:

* If a package comes over an insecure context no contents can be treated as secure
   * Even if contents are signed they are not secure due to potential resigning
* If a package comes over a secure context
   * Same origin/`<cid>` locations treated as secure since the transfer cert is providing a secure context
* Differing origin needs cert to create a secure context
   * Required even if loading insecure resource off the differing domain to prevent impersonation

This assumes differing origins is only possible via nested packages, the spec text currently does not mandate such.

**Comment by lrosenthol** [comment]
The cert and the origin have nothing to do with each other.  Just because
something is signed - and even if that certificate verifies just fine - you
can't use that as any type of trust that you should use a different origin.

For example, what prevents me from creating a package, signing it with my
cert but setting the origin to "badactor.com"? Or worse, taking a known
package (say jquery), signing it and remapping the origin.

Mixing origins in a single package is even worse, especially when you try
to combine it with inter-package linking...

We've been looking at this problem for a while now in the context of other
packaging models and so far we've found no good solution...

**Comment by bmeck** [comment]
@lrosenthol I'm saying your cert used for signing must have valid a valid chain of trust for `badactor.com` if you state an origin for `badactor.com`. The process to validate that a cert belongs to `badactor.com` is something that exists in the web world. However, this becomes complicated once we talk about offline verification since the full chain of trust needs to be verified and things like OCSP are not possible.

Mixing origins I think should be fine if the mixing is only at package boundaries:

```
foo.com.webpackage (signed by foo.com cert, sets origin for contents to foo.com)
\- index.html
\- foo.js
\- bar.com.webpackage (must include Package Signature, sets origin for contents to bar.com)
    \- bar.js
    \- Content Index <- ALL SIGNED BY bar.com
       \- bar.js
       \- Pub key
    \- Pub Key
\- Content Index <- ALL SIGNED BY foo.com
    \- index.html
    \- foo.js
    \- bar.com.webpackage
    \- Pub Key
\- Pub Key
```

I think in particular the passing of pubkeys around is influenced by things such as [Google's attemp for Pub Key transparency](https://security.googleblog.com/2017/01/security-through-transparency.html).

@lrosenthol Do you have a quick list of the problems you have experienced in the past?

**Comment by lrosenthol** [comment]
@bmeck - Yes, SSL certs do indeed work for origins because that's what they
were designed to do.  But other types of certs don't have that feature.
And you can't use the email address of the person/organization as the
origin, because my company could own many domains.  (let's keep offline,
off the table, for now)

And I think we agree that you can't specify an origin unless you have a
cert that verifies to that origin (once we figure out how that would work).

So in your example, for the bar.com.webpackage, bar.js would have an
absolute URL of https://bar.com/bar.js - since it's origined off bar.com.
Correct?  And it refers to a relative URL "image.jpg", that would then need
to resolve to https://bar.com/image.jpg, correct?  I'm conflicted on if
that is a good or bad thing.

I wasn't aware of the Key Transparency effort - that's interesting - but
until (or if) it gets any real traction, I dont think its prudent to build
a system around...

**Comment by bmeck** [comment]
> I wasn't aware of the Key Transparency effort - that's interesting - but
until (or if) it gets any real traction, I dont think its prudent to build
a system around...

Agree other existing efforts like PGP Key Servers have similar lookup mechanisms already. It is something to think about.

> So in your example, for the bar.com.webpackage, bar.js would have an
absolute URL of https://bar.com/bar.js - since it's origined off bar.com.
Correct?  And it refers to a relative URL "image.jpg", that would then need
to resolve to https://bar.com/image.jpg, correct?  I'm conflicted on if
that is a good or bad thing.

This I am a bit fuzzy on. Web has a concept of "base URL" to change the root of relative lookups fo a resource; I see no reason why it couldn't have something like `base-url = bar.com/wepackages/1/` and then `bar.js` is treated as `bar.com/wepackages/1/bar.js`. It has the same escape properties as a naive `chroot` or a cookie `path` attribute which needs to be taken into consideration.

> Yes, SSL certs do indeed work for origins because that's what they
were designed to do.  But other types of certs don't have that feature.
And you can't use the email address of the person/organization as the
origin, because my company could own many domains.  (let's keep offline,
off the table, for now)

It is exactly non-SSL certs that are my interest here. I don't have a good definition for example of what a `secure context` is for filesystem based things that Node/Electron want. It isn't a www domain. Verifying would require some local keychain at the very minimum.

**Comment by lrosenthol** [comment]
> Web has a concept of "base URL" to change the root of relative lookups fo a resource; I see no reason why it couldn't have something like base-url = bar.com/wepackages/1/ and then bar.js is treated as bar.com/wepackages/1/bar.js.

I agree, that would also apply.  But in lieu of that, we have to assume it's right at the root, yes?

>>Yes, SSL certs do indeed work for origins because that's what they
were designed to do. But other types of certs don't have that feature.

>It is exactly non-SSL certs that are my interest here. I don't have a good definition for example of what a secure context is for filesystem based things that Node/Electron want. It isn't a www domain. Verifying would require some local keychain at the very minimum.

Bingo!   That is exactly the problem.  
Or one part of the problem

Actually, establishing a secure context is easy - a caller such as Node/Electron can easily establish that the content they are displaying in their "web view" must be in a secure context - regardless of where it comes from.   In fact, I would say that just like the many browsers are moving to https only ([here](https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/) and many other places), web-packages should also only run in secure context.

But secure context has nothing to do with the origin.  The question here is whether you need the origin or not.  The only reason you would need one is if you expect the package to reference resources outside of itself, and therefore are concerned about CORS-like considerations.  Otherwise, you could simply consider the package as the origin (and each sub-package is either its own origin or a [sub-origin](https://w3c.github.io/webappsec-suborigins/).)

It's exactly this problem (origin vs. context) that has been plaguing us and others as well...

**Comment by bmeck** [comment]
> I agree, that would also apply. But in lieu of that, we have to assume it's right at the root, yes?

Up to UA, base URL depends on location of the HTML in web views. Could implicitly do URL resolve on browser side to get `http://foo.com/1.webpackage` => `http://foo.com/1.webpackage/` so `bar.js` would be `http://foo.com/1.webpackage/bar.js`. This behavior is similar to what https://github.com/bmeck/noda-loader did on filesystem locations.

> Actually, establishing a secure context is easy - a caller such as Node/Electron can easily establish that the content they are displaying in their "web view" must be in a secure context - regardless of where it comes from. In fact, I would say that just like the many browsers are moving to https only (here and many other places), web-packages should also only run in secure context.

Node for example doesn't have any "view". It should remain possible to run non-signed applications.

Policies on if your secure context is allowed to load insecure contexts is complicated in this sense. If I download some 3rd party package, I need my non-signed application to be able to use it, and maybe vice-versa (for example `webpack` used `.js` files for configuration).

> But secure context has nothing to do with the origin. The question here is whether you need the origin or not. The only reason you would need one is if you expect the package to reference resources outside of itself, and therefore are concerned about CORS-like considerations. Otherwise, you could simply consider the package as the origin (and each sub-package is either its own origin or a sub-origin.)

Agree. While I worked on this a few years back we were thinking of a policy where origin is recorded at time of transfer of the package and is up to the host to maintain. The download would be stored in some DB with the origin setup that is not mutable by user code (for `node` this requires OS/FS permissions to be done properly).

I need to think on this some after these points.

**Comment by lrosenthol** [comment]
> Node for example doesn't have any "view". It should remain possible to run non-signed applications.

I don't see why signing of the applications has any impact on whether to force a secure context or not.  I would think that forcing secure context on all applications - regardless of whether they are signed or not - is a good thing.  It prevents non-signed applications from doing things they shouldn't be doing (IMO).  However, I could see needing to be more lenient with apps than with publications.

 > we were thinking of a policy where origin is recorded at time of transfer of the package and is up to the host to maintain

For signed packages, you could have the origin as part of the package.  As long as the signature is verified and *trusted(!)*, then there would be no problem using that origin.  It's when it's not signed (which we expect to the normal case for publications) or there is no trust that we are back to square one.

**Comment by bmeck** [comment]
@lrosenthol node has permission to access a shell / the real file system / etc. removing this is not possible at this point. Determining if something is *not-approved* for secure access is possible though.

> For signed packages, you could have the origin as part of the package. As long as the signature is verified and trusted(!), then there would be no problem using that origin. It's when it's not signed (which we expect to the normal case for publications) or there is no trust that we are back to square one.

In `node`'s case that would be the current behavior, which is to allow full access. It would need a keystore to limit this behavior.

**Comment by lrosenthol** [comment]
@bmeck - yes, for Node, I fully understand the problem/situation.  That is
indeed more complex than for publications, where we would never want to
allow access to such things.

I assume that any UA that will process webpackages is going to either need
their own personal keystore and/or use the one provided by the OS.  I don't
see how you can get away from that, especially when trust needs to be
established.

**Comment by hayatoito** [comment]
Closing as per `consider-closing`.
