### ISSUE TITLE
HTML integration

### ISSUE THREAD

**Issue by matthewp** [WICG/webpackage#73]
Hello, is it within the scope to define (or speculate) on how a person might load a webpackage in an HTML document, and what the browser should do when it unpacks a package?

Or is the idea that a document might request `GET /app.js` (from a script tag) and the server would reply with a webpackage, making any other resources that are later requested come from that package?

Thanks!

**Comment by jyasskin** [comment]
Yes, that's in scope. That's probably the main subject of the specification that'll go through the W3C.

**Comment by bmeck** [comment]
In the history of this, the idea was WebPackage is a cache filling mechanism. So I would presume (don't count it as truth) that all environments using WebPackage including HTML would accept any request responding with WebPackage appropriately to fill things out.

For Node, that is with a file extension.
For Web, that is with a MIME Type.

So, if `./app.js` in Web returns a Webpackage we have a slight problem. `type=module` does not do aliasing for paths so Webpackage would need to declare a `main` field somewhere I would presume. For Node it follows the standard resolution, but that resolution is problematic for Web since it requires resolution with IO involved.

I would go through WHATWG/W3C for figuring that out.

**Comment by matthewp** [comment]
Going to close as whatwg will likely define this.

**Comment by jyasskin** [comment]
Well, the WHATWG will only define this if our work in this repository results in a proposal to them. I'm working on writing one, so it's fine to have closed this issue, but I'll want reviewers when I send the PR.

**Comment by bmeck** [comment]
Ill be at the ready
