### ISSUE TITLE
Registered protocol handlers

### ISSUE THREAD

**Issue by annevk** [WICG/webpackage#735]
> If a URL is available from an attached bundle, the browser must retrieve it from the bundle, instead of using any registered custom protocol handler for its scheme.

How does that work given that registered protocol handlers are only for navigations?

**Comment by hayatoito** [comment]
A good question. The resource in a bundle can be specified in `<iframe>`'s `src` attribute in the page, where I guess a registered protocol handler can intercept a navigation, theoritically?

eg. the main page:
```
<script type=webbundle>
{
  source: "./a.wbn",
  resources: ["a.html", "b.html"],
}
</script>

<iframe src="a.html">
<iframe src="b.html">
```

The related issues are:

- https://github.com/WICG/webpackage/issues/650
- https://github.com/WICG/webpackage/pull/629#pullrequestreview-603306066

, where we've tried to prevent a registered custom protocol handler from intercepting a following subframe navigation:

```
<script type=webbundle>
{
  source: "./a.wbn",
  resources: ["urn:uuid:aaaa"],
}
</script>

<iframe src="urn:uuid:aaaa">  // We want to make sure urn:uuid:aaaa is retrieved from a bundle here.
```

Note that we no longer uses `urn:uuid:*` scheme. Now we are using `uuid-in-package:` scheme.

The example is:
https://github.com/WICG/webpackage/blob/main/explainers/subresource-loading-opaque-origin-iframes.md#the-main-document

**Comment by annevk** [comment]
I see, note that `<iframe src>` is not a subresource so if that's included in the scope you want to advertise that more clearly.

Is what you want here to make it possible to fallback to register protocol handler? Otherwise I'd suggest using schemes here that cannot be registered in the first place.

**Comment by irori** [comment]
> Is what you want here to make it possible to fallback to register protocol handler? Otherwise I'd suggest using schemes here that cannot be registered in the first place.

`uuid-in-package:` cannot be registered because the [normalize protocol handler parameters](https://html.spec.whatwg.org/multipage/system-state.html#normalize-protocol-handler-parameters) algorithm throws an error. That's why we switched from `urn:` to `uuid-in-package:` (https://github.com/WICG/webpackage/pull/677).

I think we can just remove the sentence

> If a URL is available from an attached bundle, the browser must retrieve it from the bundle, instead of using any registered custom protocol handler for its scheme.

from the explainer.

**Comment by hayatoito** [comment]
Thanks. Responses inline.

> if that's included in the scope you want to advertise that more clearly.

That makes sense. I agree we want to make it clear because "Subresource Loading ..." might not imply a navigation. Clarifying it in the explainer would be helpful for a reader.

> `uuid-in-package:` cannot be registered because the [normalize protocol handler parameters](https://html.spec.whatwg.org/multipage/system-state.html#normalize-protocol-handler-parameters) algorithm throws an error. That's why we switched from `urn:` to `uuid-in-package:` (#677).
> 
> I think we can just remove the sentence

I agree we should remove the sentence from the explainer. It seems [this section](https://github.com/WICG/webpackage/blob/main/explainers/subresource-loading-opaque-origin-iframes.md#alternatives-considered ) clarified the reason of introducing a new scheme. That seems enough.
