### ISSUE TITLE
Subverting path-based CSP

### ISSUE THREAD

**Issue by martinthomson** [WICG/webpackage#737]
The explainer provides [an example](https://github.com/WICG/webpackage/blob/main/explainers/subresource-loading.md#content-security-policy-csp) of where CSP is used to govern what is loaded.  In this example, only the `/script/` path is on the allowlist for `script-src`.  Presumably, there are controls in the server that ensure that scripts served from that path are safe.  The idea with that CSP is that an attacker that gains access to other resources on the server cannot use that access to inject script.

...until bundling comes along.  With the example, an attacker that compromises any resource on the server can then inject a `<script type="webbundle">` that points to their bundle, which then claims to contain content for resources under `/script/`.  The example directly shows this sort of substitution, though the bundle is higher in the tree, so it's possible I missed a clause somewhere that prevents `/bar/` speaking for `/foo/`.

**Comment by hayatoito** [comment]
Thanks for filing an issue and explanation!

I tried to figure out how an attack happens, but probably it is worth noting that we have a Path Restriction rule, as Service Workers has, which prevents /bar/ speaking for /foo/.

> Records the resources and delays fetching a subresource specified there if a subresource's origin is the [same origin](https://html.spec.whatwg.org/#same-origin) as the bundle's origin and its [path](https://url.spec.whatwg.org/#concept-url-path) contains the bundle's path as a prefix.

Note the explainer’s wording is a bit inaccurate (tracked in #732).

Given we have a Path Restriction rule, my understanding is:
- If an attacker can compromise a resource under `/script` (or `/`), the game ends.
- If an attacker can compromise a resource under `/foo`, and inject `<script type=webbundle>` into that, as follows,
```
<script type=webbundle>
{
  "source": "/foo/evil.wbn",
  "resources": ["/script/evil.js"],
}
```

In this case, a browser doesn't load  `/script/evil.js` from `/foo/evil.wbn` because it violates a Path Restriction rule; a resource's URL must start with `/foo/` in this case.

I hope we don't have any security flaw here. If we miss something, we'd appreciate further feedback.

**Comment by hayatoito** [comment]
[Issue Triage]
It seems we can close this issue.
