### ISSUE TITLE
Index should use a common structured format (eg. JSON)

### ISSUE THREAD

**Issue by lrosenthol** [WICG/webpackage#8]
Having the index file be in a text-like format that (a) doesn't specify or mandate an encoding and  (b) no provisions for proper data typing, (c) requires writing a custom parser and (d) will need a newly defined MIME type (see issue #9 ) - doesn't seem like a good idea.

I recommend instead that the index be a well defined JSON grammar.  That way standard parsers can be used and there is no question about encodings, data types, etc.

**Comment by bmeck** [comment]
@lrosenthol are there any use cases you can think of that are not solved by HTTP style header mappings that JSON would be better at. I am hesitant to have custom JSON properties but [SourceMaps](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit) have precedent of allowing this by `x_*` as a prefix. I also am concerned about deeply nested objects but with any custom header it would be possible to make the value itself an object, so that seems fine.

If you want to write up a schema that would be great :).

**Comment by lrosenthol** [comment]
The main issues are (1) data typing and (2) containers/lists.  if the data
isn't typed (eg. always treated as a string), you will introduce numerous
parsing and potential security risks.  But if I know something is a number
(or boolean or ...), then the issues go away.   Same with having a list of
things - each implementor need not write a parser (that might have security
flaws).

I'll look at doing a schema.

**Comment by jyasskin** [comment]
#36 uses a CDDL grammar to define the index, so I think this is fixed.
